[package]
name = "stash-api"
version = "0.1.0"
authors = ["Maximilian Stock <mxmlnstock@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.20"
serde = { version = "1.0.126", features = ["derive"] }
ureq = "2.1.1"
serde_json = "1.0.78"
ratelimit = "0.4.4"
log = "0.4.14"
